start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-1 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-2 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-3 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-4 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-5 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-6 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-7 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-8 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-9 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-10 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-11 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-12 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-13 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-14 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-15 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-16 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-17 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-18 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-19 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-20 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-21 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-22 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-23 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-24 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-25 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-26 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-27 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-28 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-29 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-30 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-31 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-32 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-33 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-34 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-35 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-36 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-37 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-38 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-39 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-40 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-41 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-42 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-43 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-44 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-45 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-46 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-47 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-48 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-49 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-50 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-51 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-52 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-53 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-54 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-55 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-56 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-57 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-58 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-59 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-60 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-61 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-62 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-63 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-64 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-65 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-66 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-67 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-68 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-69 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-70 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-71 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-72 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-73 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-74 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-75 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-76 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-77 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-78 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-79 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-80 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-81 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-82 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-83 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-84 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-85 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-86 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-87 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-88 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-89 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-90 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-91 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-92 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-93 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-94 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-95 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-96 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-97 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-98 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-99 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-100 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-101 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-102 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-103 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-104 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-105 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-106 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-107 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-108 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-109 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-110 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-111 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-112 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-113 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-114 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-115 
start cmd.exe /k php CS-Dorker_v3.1.php list.txt sites-116 